"""add_createdAt column

Revision ID: 234e385060ff
Revises: cf6deb8cf165
Create Date: 2023-03-07 11:09:37.423889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234e385060ff'
down_revision = 'cf6deb8cf165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_role', sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tbl_users', sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_users', 'createdAt')
    op.drop_column('tbl_role', 'createdAt')
    # ### end Alembic commands ###
