"""role_table

Revision ID: 2817a7a38738
Revises: 
Create Date: 2023-03-07 10:53:33.442928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2817a7a38738'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('role_status', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_role')
    # ### end Alembic commands ###
