"""membership

Revision ID: 292bb9b8aa76
Revises: 234e385060ff
Create Date: 2023-03-10 15:57:18.791658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292bb9b8aa76'
down_revision = '234e385060ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_name', sa.String(), nullable=False),
    sa.Column('Membership_price', sa.Float(), nullable=False),
    sa.Column('validity', sa.Integer(), nullable=False),
    sa.Column('customer_count', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_machanic_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('membership_name', sa.String(), nullable=False),
    sa.Column('payment_status', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('purchase_date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['tbl_membership.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_machanic_membership')
    op.drop_table('tbl_membership')
    # ### end Alembic commands ###
