"""add_field_membership

Revision ID: 307ee50daa6c
Revises: 292bb9b8aa76
Create Date: 2023-03-10 16:01:38.052105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307ee50daa6c'
down_revision = '292bb9b8aa76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_machanic_membership', sa.Column('paid_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_machanic_membership', 'paid_amount')
    # ### end Alembic commands ###
