"""Add fields

Revision ID: 5c26094a1f43
Revises: 307ee50daa6c
Create Date: 2023-03-12 19:38:42.705591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c26094a1f43'
down_revision = '307ee50daa6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tbl_users', sa.Column('status', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_users', 'status')
    op.drop_column('tbl_users', 'description')
    # ### end Alembic commands ###
