"""empty message

Revision ID: 81fce6b5584c
Revises: ca50ba0b1365
Create Date: 2023-03-16 09:33:54.281575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fce6b5584c'
down_revision = 'ca50ba0b1365'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_services', sa.Column('service_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_services', 'service_rating')
    # ### end Alembic commands ###
