"""add_service _table

Revision ID: ca50ba0b1365
Revises: f2db3848bffd
Create Date: 2023-03-14 10:32:18.533781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca50ba0b1365'
down_revision = 'f2db3848bffd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('machanic_id', sa.Integer(), nullable=False),
    sa.Column('macahnic_name', sa.String(), nullable=True),
    sa.Column('call_center_id', sa.Integer(), nullable=True),
    sa.Column('attender_name', sa.String(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('service_location', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('Approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('service_status', sa.String(), nullable=True),
    sa.Column('service_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['call_center_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machanic_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_services')
    # ### end Alembic commands ###
