"""user_table

Revision ID: cf6deb8cf165
Revises: 2817a7a38738
Create Date: 2023-03-07 11:07:45.587657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6deb8cf165'
down_revision = '2817a7a38738'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_no', sa.BigInteger(), nullable=False),
    sa.Column('alternate_phone_no', sa.BigInteger(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('town_city', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('pincode', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_name', sa.String(), nullable=True),
    sa.Column('vehicle_no', sa.String(), nullable=True),
    sa.Column('vehicle_make', sa.Integer(), nullable=True),
    sa.Column('vehicle_brand', sa.String(), nullable=True),
    sa.Column('driving_license_no', sa.String(), nullable=True),
    sa.Column('kyc', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_role.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_users')
    # ### end Alembic commands ###
